-- NCD (Non-Communicable Disease) care tracking for patient profiles.

CREATE TABLE IF NOT EXISTS patient_ncd_conditions (
    ncdId INT NOT NULL AUTO_INCREMENT,
    patientId INT NOT NULL,
    conditionType ENUM(
        'diabetes_type_1',
        'diabetes_type_2',
        'hypertension',
        'cardiovascular',
        'asthma',
        'copd',
        'cancer',
        'chronic_kidney_disease',
        'sickle_cell',
        'mental_health',
        'obesity',
        'other'
    ) NOT NULL,
    conditionName VARCHAR(150) NULL,
    diagnosisDate DATE NULL,
    icd10Code VARCHAR(20) NULL,
    status ENUM('active', 'controlled', 'uncontrolled', 'stable', 'worsening', 'resolved') NOT NULL DEFAULT 'active',
    riskFactors TEXT NULL,
    treatmentPlan TEXT NULL,
    targetBp VARCHAR(30) NULL,
    targetGlucose VARCHAR(30) NULL,
    smokingStatus ENUM('never', 'former', 'current', 'unknown') DEFAULT 'unknown',
    alcoholUse ENUM('none', 'occasional', 'regular', 'heavy', 'unknown') DEFAULT 'unknown',
    enrolledDate DATE NULL,
    nextReviewDate DATE NULL,
    notes TEXT NULL,
    managedBy INT NULL,
    isActive TINYINT(1) NOT NULL DEFAULT 1,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ncdId),
    INDEX idx_patient_ncd_patient (patientId),
    INDEX idx_patient_ncd_status (status),
    INDEX idx_patient_ncd_next_review (nextReviewDate),
    FOREIGN KEY (patientId) REFERENCES patients(patientId) ON DELETE CASCADE,
    FOREIGN KEY (managedBy) REFERENCES users(userId) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS patient_ncd_follow_ups (
    followUpId INT NOT NULL AUTO_INCREMENT,
    ncdId INT NOT NULL,
    patientId INT NOT NULL,
    followUpDate DATE NOT NULL,
    controlStatus ENUM('controlled', 'uncontrolled', 'improved', 'stable', 'worsening') NOT NULL DEFAULT 'stable',
    bpSystolic INT NULL,
    bpDiastolic INT NULL,
    weightKg DECIMAL(6, 2) NULL,
    heightCm DECIMAL(6, 2) NULL,
    bmi DECIMAL(5, 2) NULL,
    bloodGlucose DECIMAL(6, 2) NULL,
    hba1c DECIMAL(4, 2) NULL,
    adherenceNotes TEXT NULL,
    complications TEXT NULL,
    planAdjustment TEXT NULL,
    nextReviewDate DATE NULL,
    notes TEXT NULL,
    recordedBy INT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (followUpId),
    INDEX idx_ncd_follow_up_ncd (ncdId),
    INDEX idx_ncd_follow_up_patient (patientId),
    INDEX idx_ncd_follow_up_date (followUpDate),
    FOREIGN KEY (ncdId) REFERENCES patient_ncd_conditions(ncdId) ON DELETE CASCADE,
    FOREIGN KEY (patientId) REFERENCES patients(patientId) ON DELETE CASCADE,
    FOREIGN KEY (recordedBy) REFERENCES users(userId) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
